language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: AXuIf8NOq6xyJ70w17Qq/cH07pVQrtWahP8jRgjxBjpBby5e8JMa1f79ipzVD3EqcvYkzGbTY2Yf+T1h5lVgQbS3d/T1Wxjy3PCXMoQZZqRp8E2KjIneucrW9HtbaTWhJTF6OYmJIjogtdBeO8DlXepbiHTwIAv9RkswW77LySE=
